### ISSUE TITLE
InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device

### ISSUE THREAD

**Issue by ryanzor** [firebase/FirebaseUI-Android#133]
Using a Samsung S6 with play services 9.0.83 the app crashes when I try to login via email.  I either select a google email or type an email in and then I get a crash with the following log:

> 05-22 10:50:17.887 19853-19853/com.ryanzor.thegang E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                      Process: com.ryanzor.thegang, PID: 19853
>                                                                      com.google.android.gms.tasks.RuntimeExecutionException: com.google.firebase.FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.
>                                                                          at com.google.android.gms.tasks.zzh.getResult(Unknown Source)
>                                                                          at com.firebase.ui.auth.ui.AcquireEmailHelper$1.onComplete(AcquireEmailHelper.java:57)
>                                                                          at com.google.android.gms.tasks.zzc$1.run(Unknown Source)
>                                                                          at android.os.Handler.handleCallback(Handler.java:739)
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                          at android.os.Looper.loop(Looper.java:158)
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:7229)
>                                                                          at java.lang.reflect.Method.invoke(Native Method)
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
>                                                                       Caused by: com.google.firebase.FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.
>                                                                          at com.google.android.gms.internal.zznp$zzb.zzv(Unknown Source)
>                                                                          at com.google.android.gms.internal.zzoj$zzc.zzz(Unknown Source)
>                                                                          at com.google.android.gms.internal.zzoj$zzc.onConnectionFailed(Unknown Source)
>                                                                          at com.google.android.gms.internal.zzoj$zzd.zzh(Unknown Source)
>                                                                          at com.google.android.gms.common.internal.zzd$zzk.zzl(Unknown Source)
>                                                                          at com.google.android.gms.common.internal.zzd$zza.zzc(Unknown Source)
>                                                                          at com.google.android.gms.common.internal.zzd$zza.zzw(Unknown Source)
>                                                                          at com.google.android.gms.common.internal.zzd$zze.zztr(Unknown Source)
>                                                                          at com.google.android.gms.common.internal.zzd$zzd.handleMessage(Unknown Source)
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                          at android.os.Looper.loop(Looper.java:158)
>                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

As far as I can tell everything is correctly enabled on my firebase console and in app.  This crash happens on the app I built myself and the example app.

**Comment by iainmcgin** [comment]
Hi,

We've seen this issue occur in a few separate reports now; the issue is with the underlying Firebase Auth library rather than Firebase UI. We're working with the play services team to find a resolution.

**Comment by SahajRana** [comment]
Error in log..

`E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.rana.sahaj.myyu-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.rana.sahaj.myyu-2, /vendor/lib, /system/lib]]`

Is it fixed ?
because I didn't got its solution yet

**Comment by katowulf** [comment]
Hi Gents, This is an SDK issue. You can view product issues on our [support page](https://firebase.google.com/support/) and our [status page](https://status.firebase.google.com). Here's the latest:  https://status.firebase.google.com/incident/Authentication/16001.

Hang in there, pretty much everyone is working on this one.
![image](https://cloud.githubusercontent.com/assets/959972/15623560/debb2a10-2429-11e6-8a0a-ebeffd280e77.png)

**Comment by alfongj** [comment]
This [has been resolved in SDK 9.0.2](https://status.firebase.google.com/incident/Authentication/16001)

Please update to 9.0.2 and you should no longer experience this issue.

**Comment by samtstern** [comment]
Closing issue since this should be fixed with `9.0.2` and this library has been upgraded to that version.  Please feel free to comment here if you continue to see this problem in the future.

**Comment by mufaddalgulshan** [comment]
I still get an error on my Galaxy S6

`E/GmsClient: unable to connect to service: com.google.firebase.auth.api.gms.service.START on com.google.android.gms`

**Comment by ryanzor** [comment]
Also not working on my galaxy s6, does work on an emulated nexus 6P

**Comment by langhoangal** [comment]
Confirm that it still happen!

After updating to 9.0.2, with the same code part, i tested on two devices (HTC A9 & Xiaomi Redmi Note 3) then it still happened on Xiaomi device.

**Comment by alouanemed** [comment]
Confirm that it still happen!

Nexus 5 ; Android 6

**Comment by aymenlaadhari** [comment]
Still happen !

**Comment by langhoangal** [comment]
As i remember, after removing things related to google auth (since i don't need it for my app) then it works. You can give a try!

**Comment by easuno** [comment]
Still happened on **HTC Butterfly** with Google Play Service v9.4.52, Android API:  19,
using firebase auth version:  `compile 'com.google.firebase:firebase-auth:9.2.0'`

**Comment by Alcasser** [comment]
Happening with 9.6.1

**Comment by samtstern** [comment]
@Alcasser does this happen on a specific device?  If so would you be willing to reproduce it and provide a bugreport?  I could give you instructions.

**Comment by asinel** [comment]
@samtstern it happens with my Nexus 5X + Android 7.0
Firebase-auth version is 9.6.1

**Comment by samtstern** [comment]
@asinel sounds like you can get this to happen on a real device, can you do me a favor and send some more information?

  * What version of Google Play Services is on your device (**Settings > Apps > Google Play Services**)
  * Could you capture a bugreport and email it to me at samstern@google.com?  Just go to **Developer Options > Take Bug Report** and then wait a few minutes, you'll have a ZIP you can email.

Of course the above is all optional, the bugreport will contain a lot of info about your device so if you don't want to send it that's alright.

**Comment by asinel** [comment]
@samtstern 9.8.77(440-135396225).
It's strange, but now it works. Thank you.

**Comment by samtstern** [comment]
@asinel a bug report would be great, but only if it stops working again.  Glad it's working for you for now.

**Comment by nicbell** [comment]
I am getting `InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device` with play services version `9.8.77 (448-135396225)` on a existing app that was working until yesterday when I tried logging out and now can't log back in. 

@asinel how did you fix it?

**Comment by nicbell** [comment]
Just fixed it by clearing all data for Google Play Services.

**Comment by samtstern** [comment]
@nicbell glad you fixed it!  Almost wish you hadn't since we're dying to get a bugreport from a phone exhibiting this behavior and using the latest version of play services (which you seem to have).  If you see this again and you're willing to help out, please capture a BR 👍

**Comment by redgell** [comment]
I am getting this error running some tests on Android Wear 2.0.  Bugreport can be found here:
[BugReport](https://drive.google.com/file/d/0Bz8Ek_ymNfjhN2MxRDM3WXp4aE0/view?usp=sharing)

**Comment by InHwanPark** [comment]
stiill getting error on lg g3 and nexus
com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred.
                     at com.google.android.gms.internal.zzahe.zzfc(Unknown Source)
                     at com.google.android.gms.internal.zzahb$zzg.zza(Unknown Source)
                     at com.google.android.gms.internal.zzahm.zzfd(Unknown Source)
                     at com.google.android.gms.internal.zzahm$zza.onFailure(Unknown Source)
                     at com.google.android.gms.internal.zzahh$zza.onTransact(Unknown Source)
                     at android.os.Binder.execTransact(Binder.java:453)

**Comment by Max01010101010101** [comment]
Wow, is 2017 and I am still getting this error in the Firebase-auth:10.2.1
So I guess, Google is just tired to try to fix it, and we gonna live with this bug **forever**.

**Comment by Max01010101010101** [comment]
I have try in multiple emulators. (more than 4)

**Comment by katowulf** [comment]
@Max01010101010101 please keep your comments civil (I'm redacting them). We're developers with jobs, just like you. If you want to contribute to the discussion, please submit a bug report so we can troubleshoot. We'd love to see this solved as much as you would.

**Comment by nhuthuynh** [comment]
i have the same issue. I am using com.google.android.gms:play-services-ads:11.2.0 and com.google.firebase:firebase-auth:11.2.0. I run my application on Emulator Genymotion v2.9.0 and Virtual devices: Google Nexus 5X - 7.0.0 - API 24 - 1080x1920

`com.google.firebase.FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.
                                                                                        at com.google.firebase.zzb.zzr(Unknown Source)
                                                                                        at com.google.android.gms.common.api.internal.zze.zzq(Unknown Source)
                                                                                        at com.google.android.gms.common.api.internal.zzbr.zzu(Unknown Source)
                                                                                        at com.google.android.gms.common.api.internal.zzbr.onConnectionFailed(Unknown Source)
                                                                                        at com.google.android.gms.common.api.internal.zzbr.connect(Unknown Source)
                                                                                        at com.google.android.gms.common.api.internal.zzbr.zza(Unknown Source)
                                                                                        at com.google.android.gms.common.api.internal.zzbp.handleMessage(Unknown Source)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)`

Project Gradle 
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.0.0'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://maven.google.com/"}
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

app gradle:

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "au.edu.csu.itc209.letseat"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.google.android.gms:play-services-ads:11.2.0'
    //compile 'com.google.android.gms:play-services:11.2.0'
    compile 'com.google.firebase:firebase-auth:11.2.0'
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile 'com.google.android.gms:play-services-auth:11.2.0'
    compile 'com.google.firebase:firebase-messaging:10.0.1'
    compile 'com.google.firebase:firebase-database:10.0.1'
    testCompile 'junit:junit:4.12'
}





apply plugin: 'com.google.gms.google-services'`

**Comment by qiuuu** [comment]
I solved same problem through adding google service in genymotion.
