### ISSUE TITLE
WelcomeBackIDPPrompt cancels sign in prematurely

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#348]
While working on #349, I ran into an interesting issue that I'm pretty sure affect all users of 0.6.0. Here was the config I ran with:
![image](https://cloud.githubusercontent.com/assets/9490724/19257228/bb247cd2-8f22-11e6-866e-4ef644da8978.png)
- Android device: 6P
- Android OS version: 7.0
- Google Play Services version: 9.6.83

Here's some debugging:
![image](https://cloud.githubusercontent.com/assets/9490724/19257321/72845870-8f23-11e6-8392-93672e560615.png)
I haven't had time to look into this issue in great detail, but `mIdpProvider` ends up being null because of `providerParcel` disagreeing with `mProviderId` about what the provider is. BTW, tests are happy.

BTW: I disabled smart lock, started AuthUI with only the email provider, and here is my existing user: 
![image](https://cloud.githubusercontent.com/assets/9490724/19257290/2e1c6146-8f23-11e6-9278-db79b7dbb217.png)

**Comment by SUPERCILEX** [comment]
I figured out why this stuff is happening: if the Smart Lock credential saved is from Google (or any other provider), but the AuthUI flow doesn't enable that provider, this issue happens. I don't know if this needs to be fixed since people will normally stick with the same providers if they are calling the auth flow from different places in their app.

**Comment by SUPERCILEX** [comment]
I discovered another bug related to this issue: if you enable smart lock and save a credential, sign out and then start the auth flow again without enabling smart lock, the blue bar showing the smart lock info still shows up and the user is not signed in (that bit is expected behavior, but the blue bar at the bottom is not).

**Comment by SUPERCILEX** [comment]
I don't know why it didn't close itself, fixed in #357.

**Comment by samtstern** [comment]
@SUPERCILEX I like to keep things open and "fix-implemented" until they've actually been released, otherwise people get confused why they're still experiencing "closed" bugs

**Comment by SUPERCILEX** [comment]
Sounds good!

**Comment by samtstern** [comment]
The fix for this issue has been released in version `1.0.1`.
