### ISSUE TITLE
onActivityResult is not called for phone auth.

### ISSUE THREAD

**Issue by owcs** [firebase/FirebaseUI-Android#750]
* Android device: OnePlus One
  * Android OS version: 7.1.2
  * Google Play Services version: 11.0.55
  * Firebase/Play Services SDK version: 11.0.0
  * FirebaseUI version: 2.0.0
  
### Describe the problem:

onActivityResult is not called for cancelled/successful phone auth

#### Steps to reproduce:

1. Start phone number verification.
2. Cancel phone number verification.
  
#### Observed Results:

onActivityResult is not called.
  
#### Expected Results:

onActivityResult is called when cancelled or successful.
  
#### Relevant Code:

  ```
startActivityForResult(
    AuthUI.getInstance()
        .createSignInIntentBuilder()
        .setAvailableProviders(
            Arrays.asList(
                new AuthUI.IdpConfig.Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build())
            )
        .build(),
    RC_SIGN_IN);

  ```
Maybe due to `RC_PHONE_FLOW` not being handle in [SignInDelegate.java](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/util/signincontainer/SignInDelegate.java#L178)?

**Comment by samtstern** [comment]
@owcs thanks for reporting this and also for pointing at a possible solution in `SignInDelegate`.  I will take a look.

**Comment by geolyth** [comment]
The same issue happens to me...in code of SignInDelegate.java I read:

```
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case RC_CREDENTIALS_READ:
                if (resultCode == ResultCodes.OK) {
                    // credential selected from SmartLock, log in with that credential
                    Credential credential = data.getParcelableExtra(Credential.EXTRA_KEY);
                    handleCredential(credential);
                } else {
                    // Smart lock selector cancelled, go to the AuthMethodPicker screen
                    startAuthMethodChoice();
                }
                break;
            case RC_IDP_SIGNIN:
            case RC_AUTH_METHOD_PICKER:
            case RC_EMAIL_FLOW:
                finish(resultCode, data);
                break;
            default:
                IdpSignInContainer signInContainer = IdpSignInContainer.getInstance(getActivity());
                if (signInContainer != null) {
                    signInContainer.onActivityResult(requestCode, resultCode, data);
                }
        }
    }
```

**Comment by mcbtony** [comment]
I am facing the same issue too. After verified the SMS code, onActivityResult() is not called

**Comment by geolyth** [comment]
Seems that @samtstern fix this on next release. We have to wait version 2.0.1 ;)

**Comment by samtstern** [comment]
This is fixed in `2.0.1`

**Comment by tatanka987** [comment]
Issue still reproduce in version 2.3.0 on Galaxy Nexus (Android 4.3) and on Samsung Galaxy S4 (Android 4.2.2) maybe on other devices with Android 4.x.x. In this case onActivityResult called immediately after press button "Verify phone number" with null IdpResponse.
