### ISSUE TITLE
Remove libphonenumber validation from client-side

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#812]
Some valid numbers (esp Indian it seems) are being rejected on the client side due to phone number validation in Android platform being out of date.

The resolution is to remove all validation from the client side and allow the server side to reject badly formatted numbers.

**Comment by samtstern** [comment]
cc @ashwinraghav

**Comment by ashwinraghav** [comment]
The phone number validation is used in two flows:
1) When a user types in their phone and submits.
2) When the hint selector returns the number.

2) is fixed in the ongoing gms release. Once complete, it might be safe to simply remove this validation. A good test to ensure the change does not regress would be to test if the hint selector response results in acceptable behavior on TMobile AND Verizon sim cards.

**Comment by HammadNasir** [comment]
This issue has not been resolved yet and I'm facing similar issue while trying it with by 'Airtel' phone number here in India.

**Comment by samtstern** [comment]
The fix for the first part of this issue was released in version `2.2.0`.  A complete fix will be available in a week or two after the next release of Google Play services.

**Comment by 100rabhkr** [comment]
Hello, is this issue resolved ? I am facing similar problems with my number

**Comment by samtstern** [comment]
@100rabhkr this issue should be resolved in almost all cases.  The only remaining case is when the phone number is provided to FirebaseUI by SmartLock.

**Comment by 100rabhkr** [comment]
so should I change it to latest versions will it work?

**Comment by samtstern** [comment]
I believe #1023 removes the last of this.

**Comment by samtstern** [comment]
This is fixed in version `3.1.1`.

**Comment by Ankur008** [comment]
but this problem is still there( only happens with Reliance Jio Phone no), If I am sending phone no with country code than it is working. but when I am trying without country code then it is not working. 
using firebase auth lib version 11.8.0
