### ISSUE TITLE
Welcome Back screen appears on email signup when saving by pressing enter on keyboard

### ISSUE THREAD

**Issue by harvitronix** [firebase/FirebaseUI-Android#869]
### Describe your environment

  * Android device: Emulator
  * Android OS version: 7.1.1
  * Google Play Services version: 11.0.4
  * Firebase/Play Services SDK version: 11.0.4
  * FirebaseUI version: 2.2.0
  
### Describe the problem:

When I create a new account using the email method, on the emulator, if I complete the sign up form by _pressing enter/return on my keyboard_, the "Welcome back!" modal appears on top of the signed in activity, even though this is a new signup. If I repeat the same steps but _click_ the Save button instead of pressing enter, the new user is created as expected, and the "Welcome back" model does not appear.

#### Steps to reproduce:

1. Create activities by following the example found here: https://github.com/firebase/FirebaseUI-Android/tree/master/app
3. Run the app in an emulator
4. Sign in with email
5. Fill out the email address input, click Next or press return
6. Fill out the First & last name and Password fields
7. Press ENTER (instead of clicking Save)

#### Observed Results:

User is created, and then immediately the "Welcome back!" screen appears. Entering the password we entered when creating the account causes a NPE:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.test.app, PID: 14783
                                                                             java.lang.NullPointerException: Activity must not be null
                                                                                 at com.google.android.gms.common.internal.zzbo.zzb(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzbdr.<init>(Unknown Source)
                                                                                 at com.google.android.gms.common.api.GoogleApiClient$Builder.enableAutoManage(Unknown Source)
                                                                                 at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish(SaveSmartLock.java:219)
                                                                                 at com.firebase.ui.auth.ui.HelperActivityBase.saveCredentialsOrFinish(HelperActivityBase.java:89)
                                                                                 at com.firebase.ui.auth.ui.accountlink.WelcomeBackPasswordPrompt$2.onSuccess(WelcomeBackPasswordPrompt.java:162)
                                                                                 at com.firebase.ui.auth.ui.accountlink.WelcomeBackPasswordPrompt$2.onSuccess(WelcomeBackPasswordPrompt.java:153)
                                                                                 at com.google.android.gms.tasks.zzj.run(Unknown Source)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

If instead of entering the password on the Welcome back screen, you press the back button the emulator, the modal goes away and you are signed in as expected.

To reiterate: This does not happen if you _click_ SAVE, rather than pressing enter on a physical keyboard. It also doesn't happen on a physical device.
  
#### Expected Results:

I expect pressing return to have the same result as clicking SAVE.
  
Another user reported a similar issue on Stack Overflow here: https://stackoverflow.com/questions/44741308/firebase-ui-auth-2-0-1-showing-multiple-welcome-back-password-prompt-screens

**Comment by SUPERCILEX** [comment]
Yeah, I've seen that before too: I'm 99.9% sure it's just an emulator bug because I can't repro on a ChromeBook. Also, the bug doesn't make sense—the `KeyEvent.KEYCODE_ENTER` event is called twice for no apparent reason.

**Comment by SUPERCILEX** [comment]
Oh lol, just saw the [StackOverflow answer](https://stackoverflow.com/a/44741554/4548500), seems like you figured it out.

**Comment by harvitronix** [comment]
After reporting the bug here, I ran into the issue on the emulator using a non-Firebase form. (Not the same Welcome screen issue, of course, but a similar strange behavior caused only by pressing return on a physical keyboard.) So it appears to have nothing to do with FirebaseUI after all! I'll close this and file a bug for the emulator. Cheers!

**Comment by samtstern** [comment]
Thanks all for following up on this!

**Comment by Kyrluckechuck** [comment]
Just came across this, wanted to report that this is still happening for me on my computer with that emulator, but can +1 it does not happen when actually pressing 'Next' in the UI. 

If i can provide anything that may help with this, please let me know, otherwise I guess I'll just have to disable the ENTER key on my keyboard in the emulator since I keep accidentally doing it out of habit X_X

**Comment by SUPERCILEX** [comment]
@everyone ok so I lied. 😢 I'm implementing keyboard shortcuts in my app and I have a much better understanding of the `KeyEvent` stuff now. Turns out we _were_ getting two events, one for the down event and one for the up event. On top of that, if you hold the key, it will continually call `onKeyDown`. Ouch! 😕 Not sure why I didn't notice this behavior on ChromeBooks, maybe they have a compatibility mode or something.

PR incoming! 😄

**Comment by Kyrluckechuck** [comment]
Ah, so glad to hear it! 😀                                                                                                                                                                                                                                                                                                                 From: notifications@github.comSent: September 1, 2017 2:40 PMTo: FirebaseUI-Android@noreply.github.comReply-to: reply@reply.github.comCc: justin@mctango.com; comment@noreply.github.comSubject: Re: [firebase/FirebaseUI-Android] Welcome Back screen appears on email signup when saving by pressing enter on keyboard (#869)  @everyone ok so I lied. 😢 I'm implementing keyboard shortcuts in my app and I have a much better understanding of the KeyEvent stuff now. Turns out we were getting two events, one for the down event and one for the up event. On top of that, if you hold the key, it will continually call onKeyDown. Ouch! 😕 Not sure why I didn't notice this behavior on ChromeBooks, maybe they have a compatibility mode or something.
PR incoming! 😄

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by samtstern** [comment]
This issue has been fixed in version `2.4.0`:
https://github.com/firebase/FirebaseUI-Android/releases/tag/2.4.0

**Comment by shimiuh** [comment]
I am still getting this crash on 3.1.0

Fatal Exception: java.lang.NullPointerException
Activity must not be null
keyboard_arrow_up
com.google.android.gms.common.internal.zzbp.zzb (Unknown Source)
com.google.android.gms.common.api.internal.zzcf.<init> (Unknown Source)
com.google.android.gms.common.api.GoogleApiClient$Builder.enableAutoManage (Unknown Source)
arrow_right
com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish (SaveSmartLock.java:219)
com.firebase.ui.auth.ui.HelperActivityBase.saveCredentialsOrFinish (HelperActivityBase.java:88)
com.firebase.ui.auth.ui.HelperActivityBase.saveCredentialsOrFinish (HelperActivityBase.java:76)
com.firebase.ui.auth.ui.idp.CredentialSignInHandler.onComplete (CredentialSignInHandler.java:67)
com.google.android.gms.tasks.zzf.run (Unknown Source)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6682)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
